"""Multiverse importer — pure business logic for adopting a standalone data_dir.

Transforms an existing standalone ``data_dir`` (the single-user ``gaottt.db`` +
FAISS cluster layout) into one universe under ``<multiverse_root>/universes/<uid>/``
with a managed manifest, a registry row, and a freshly issued API key.

Design constraints (plan §2.4 / §2.5):

* **Pure planning, side-effecting execution.** ``build_import_plan`` is a pure
  function — it produces an :class:`ImportPlan` that ``--dry-run`` can print
  without touching the filesystem. ``execute_import`` is the only mutating
  entry point and owns the transaction scope.
* **Transaction scope = max-3 retry unit.** ``allocate_port → mkdir → copy/move
  → integrity_check → manifest → registry.create_universe`` is wrapped in a
  single retry unit. IntegrityError (the partial UNIQUE INDEX on
  ``universes.port``) triggers cleanup + retry; any other exception triggers
  cleanup + re-raise. This guarantees no stray ``universes/<uid>/`` dir is left
  unregistered (which would make supervisor ``reconcile`` WARN).
* **Source identity, not past-vector identity.** ``resolve_embedder_identity``
  records ``config.embedding_dim`` as a *runtime expectation* — the real proof
  happens at target ``engine.startup`` (FAISS load + manifest check). The
  importer cannot falsify semantic drift; it only refuses to import when the
  configured embedder service is unreachable or reports a different identity.
* **Allowlist copy.** Only ``COPY_FILENAMES`` are copied; every other file
  (backups, manifests, owner locks, tokens, registry dbs) is skipped with a
  reason so the target dir is operationally clean.
"""
from __future__ import annotations

import json
import logging
import shutil
import sqlite3
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import aiosqlite

from gaottt.config import GaOTTTConfig
from gaottt.store.manifest import UniverseManifest, load_manifest, write_manifest

if TYPE_CHECKING:
    from gaottt.multiverse.registry import MultiverseRegistry

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants — copy allowlist + classification heuristics
# ---------------------------------------------------------------------------

# The 7 canonical copy targets (plan §2.3 step 6). ``-wal`` / ``-shm`` absence
# is normal (clean checkpoint completed); presence is fine too.
COPY_FILENAMES: tuple[str, ...] = (
    "gaottt.db",
    "gaottt.db-shm",
    "gaottt.db-wal",
    "gaottt.faiss",
    "gaottt.faiss.ids",
    "gaottt.virtual.faiss",
    "gaottt.virtual.faiss.ids",
)

# Substring classifiers for the ``skipped`` report. Each (substring, reason)
# pair is checked in order; the first match wins. A file that matches none and
# is not in COPY_FILENAMES gets the generic ``unrecognized`` reason.
_SKIP_CLASSIFIERS: tuple[tuple[str, str], ...] = (
    (".bak", "backup file"),
    (".before-", "pre-migration backup"),
    (".post-", "post-migration snapshot"),
    (".broken-", "broken / quarantined"),
    (".tmp", "temporary scratch file"),
    ("manifest.json", "regenerated at target (managed=True)"),
    ("owner.lock", "lease bookkeeping, regenerated by target backend"),
    ("owner.lock.guard", "lease guard, regenerated by target backend"),
    ("backend.token", "auth token, regenerated by supervisor spawn"),
    ("registry.db", "multiverse registry db (not a universe data file)"),
    ("memory.db", "legacy memory db"),
    ("?mode=ro", "legacy read-only shim"),
)

# Post-copy retry budget. The partial UNIQUE INDEX ``idx_universes_port_live``
# is the DB-level backstop against a concurrent supervisor allocating the same
# port; we retry the whole allocate→copy→manifest→create unit on
# IntegrityError so the importer self-heals instead of leaving a stray dir.
_MAX_ATTEMPTS = 3


# ---------------------------------------------------------------------------
# Dataclasses — shapes pinned by tests/unit/test_importer.py
# ---------------------------------------------------------------------------


@dataclass
class FilePlan:
    """Result of scanning ``source`` for copy targets.

    ``copy_files`` is the subset of :data:`COPY_FILENAMES` actually present.
    ``skipped`` lists every other file with a human-readable reason (for the
    dry-run report and the ``--move`` residue WARNING). ``total_bytes`` is the
    sum of ``st_size`` across ``copy_files`` — the budget for the disk-capacity
    gate (sparse files report their nominal size, which is what we want: the
    target filesystem must hold the post-copy bytes).
    """

    copy_files: list[str]
    skipped: list[tuple[str, str]]
    total_bytes: int


@dataclass
class ImportPlan:
    """A dry-run-renderable, side-effect-free import plan.

    ``port`` is ``None`` at build time and resolved inside :func:`execute_import`
    via ``registry.allocate_port`` — keeping planning pure lets ``--dry-run``
    run without a registry. ``embedding_dim`` is the *runtime expectation*
    (config-derived); it is recorded in the target manifest but is NOT a proof
    of source FAISS dimensionality. The hard check lives in
    :func:`gaottt.core.engine.GaOTTTEngine.startup` (manifest gate + FAISS load).
    """

    universe_id: str
    source: Path
    target: Path
    owner_label: str
    port: int | None
    embedder_id: str
    embedder_version: str
    embedding_dim: int
    file_plan: FilePlan
    mode: str  # "copy" | "move"


# ---------------------------------------------------------------------------
# Exceptions — distinct types so the CLI can map them to specific exit codes
# without string-matching RuntimeError messages.
# ---------------------------------------------------------------------------


class IntegrityCheckFailed(RuntimeError):
    """Post-copy ``PRAGMA integrity_check`` returned non-``ok`` (or the target
    db is missing / unopenable / schemaless).

    Raised by :func:`_verify_target_db`. The CLI maps this to exit 8.
    """


class UniverseAlreadyExistsError(RuntimeError):
    """``plan.universe_id`` is already present in the registry.

    Raised by :func:`execute_import` before the retry loop so the
    ``create_universe`` PRIMARY KEY IntegrityError is not misclassified as a
    port race. The CLI maps this to exit 2 (argument error — same as
    :func:`validate_universe_id` rejection).
    """


# ---------------------------------------------------------------------------
# Pure functions
# ---------------------------------------------------------------------------


def _classify_skip(name: str) -> str:
    for needle, reason in _SKIP_CLASSIFIERS:
        if needle in name:
            return reason
    return "unrecognized file (not in copy allowlist)"


def compute_file_plan(source: Path) -> FilePlan:
    """Scan ``source`` and partition its contents into copy targets vs skips.

    Raises ``FileNotFoundError`` / ``NotADirectoryError`` if ``source`` is not
    a readable directory — callers should let these propagate so a bad CLI
    flag fails loudly rather than silently producing an empty plan.
    """
    src = Path(source)
    if not src.exists():
        raise FileNotFoundError(f"source directory not found: {src}")
    if not src.is_dir():
        raise NotADirectoryError(f"source is not a directory: {src}")

    copy_set = set(COPY_FILENAMES)
    copy_files: list[str] = []
    skipped: list[tuple[str, str]] = []
    total_bytes = 0

    for entry in sorted(src.iterdir()):
        if not entry.is_file():
            # Subdirectories are not part of the standalone layout; report and
            # skip so the dry-run output reflects everything on disk.
            skipped.append((entry.name, "directory (not a file)"))
            continue
        if entry.name in copy_set:
            copy_files.append(entry.name)
            total_bytes += entry.stat().st_size
        else:
            skipped.append((entry.name, _classify_skip(entry.name)))

    return FilePlan(
        copy_files=copy_files, skipped=skipped, total_bytes=total_bytes,
    )


def resolve_embedder_identity(
    source_manifest: UniverseManifest | None,
    config: GaOTTTConfig,
    override_id: str | None,
    override_version: str | None,
) -> tuple[str, str, int]:
    """Resolve ``(embedder_id, embedder_version, embedding_dim)`` for the target.

    Priority: CLI override > source manifest > config fallback. ``embedding_dim``
    is **always** ``config.embedding_dim`` — the manifest's dim field records
    the runtime expectation, not a proof of source FAISS dimensionality. The
    hard dimensional check is :func:`verify_embedder_identity` at target
    ``engine.startup``, which compares the runtime embedder against both the
    manifest and the FAISS index shape.
    """
    if override_id:
        eid = override_id
    elif source_manifest is not None:
        eid = source_manifest.embedder_id
    else:
        eid = config.model_name

    if override_version:
        ever = override_version
    elif source_manifest is not None:
        ever = source_manifest.embedder_version
    else:
        # Standalone DBs typically have no pinned revision; ``unpinned`` is the
        # same sentinel :func:`ensure_manifest` writes for fresh DBs.
        ever = "unpinned"

    return eid, ever, config.embedding_dim


def validate_universe_id(uid: str) -> bool:
    """True iff ``uid`` is exactly 12 lowercase hex chars.

    Matches ``uuid4().hex[:12]`` as used by the supervisor's
    ``POST /admin/universes`` so importer-adopted universes are
    indistinguishable from supervisor-created ones.
    """
    if not isinstance(uid, str):
        return False
    if len(uid) != 12:
        return False
    return all(c in "0123456789abcdef" for c in uid)


def build_import_plan(
    source: Path,
    owner_label: str,
    config: GaOTTTConfig,
    *,
    universe_id: str | None = None,
    move: bool = False,
    embedder_id_override: str | None = None,
    embedder_version_override: str | None = None,
) -> ImportPlan:
    """Construct an :class:`ImportPlan` without side effects.

    Validates the universe_id format (raises ``ValueError`` on bad format or
    target collision). Port allocation is deferred to :func:`execute_import`
    so this function stays dry-run-safe.
    """
    src = Path(source)
    if universe_id is not None:
        if not validate_universe_id(universe_id):
            raise ValueError(
                f"universe_id must be 12 lowercase hex chars, got {universe_id!r}"
            )
        uid = universe_id
    else:
        uid = uuid.uuid4().hex[:12]

    mv_root = Path(config.multiverse_root)
    target = mv_root / "universes" / uid
    # Reject a pre-existing target dir so a re-run with the same explicit uid
    # cannot silently overwrite an imported universe. Auto-generated uids have
    # 16^12 = 2^48 space so collisions are astronomically unlikely.
    if target.exists():
        raise FileExistsError(
            f"target directory already exists: {target} "
            f"(use a different --universe-id or remove the existing universe)"
        )

    file_plan = compute_file_plan(src)
    # Tolerate a corrupt / unreadable source manifest: the importer's source
    # identity resolution falls back to config, and the real identity check
    # happens at target engine.startup anyway. A standalone DB that crashed
    # mid-manifest-write should still be importable.
    try:
        source_manifest = load_manifest(src)
    except (json.JSONDecodeError, ValueError, OSError):
        source_manifest = None
    eid, ever, dim = resolve_embedder_identity(
        source_manifest, config,
        embedder_id_override, embedder_version_override,
    )

    return ImportPlan(
        universe_id=uid,
        source=src,
        target=target,
        owner_label=owner_label,
        port=None,
        embedder_id=eid,
        embedder_version=ever,
        embedding_dim=dim,
        file_plan=file_plan,
        mode="move" if move else "copy",
    )


def _verify_target_db(target_db: Path) -> None:
    """Post-copy integrity gate.

    Three independent checks:

    1. The file must exist (a missing db means the copy silently dropped it —
       ``sqlite3.connect`` would *create* an empty file and mask the failure).
    2. ``PRAGMA integrity_check`` must return ``ok`` (catches torn writes from
       a concurrent writer that ``--force`` failed to detect).
    3. The ``nodes`` table must be present (catches an empty / schemaless file
       — SQLite treats a 0-byte file as a valid empty database, so
       ``integrity_check`` alone would pass a non-GaOTTT db through).

    Any failure raises :class:`IntegrityCheckFailed` (a ``RuntimeError``
    subclass); the caller cleans up the target dir and the CLI exits 8.
    """
    path = Path(target_db)
    if not path.exists():
        raise IntegrityCheckFailed(f"target db missing after copy: {path}")

    # ``immutable=1`` opens the file read-only without creating/resizing the
    # -wal/-shm sidecars, so a verification pass leaves no trace on the target.
    uri = f"file:{path}?immutable=1"
    try:
        conn = sqlite3.connect(uri, uri=True)
    except sqlite3.Error as exc:
        raise IntegrityCheckFailed(
            f"cannot open target db {path}: {exc}"
        ) from exc
    try:
        try:
            cur = conn.execute("PRAGMA integrity_check")
            row = cur.fetchone()
            cur.close()
        except sqlite3.DatabaseError as exc:
            raise IntegrityCheckFailed(
                f"integrity_check failed on {path}: {exc}"
            ) from exc
        if row is None or row[0] != "ok":
            raise IntegrityCheckFailed(
                f"integrity_check not ok on {path}: {row!r}"
            )
        # Schema gate: a 0-byte file passes integrity_check because SQLite
        # treats it as a valid-but-empty db. Require at least one user table
        # so an empty / schemaless source (e.g. a truncated download, or a
        # ``touch gaottt.db`` placeholder) is rejected at import time rather
        # than producing a universe whose first startup fails confusingly.
        # The deeper GaOTTT-schema check (``nodes`` table) is left to
        # ``engine.startup`` so this gate stays a pure corruption/emptiness
        # probe with no coupling to the store schema.
        try:
            cur = conn.execute(
                "SELECT COUNT(*) FROM sqlite_master "
                "WHERE type='table' AND name NOT LIKE 'sqlite_%'"
            )
            table_count = cur.fetchone()[0]
            cur.close()
        except sqlite3.DatabaseError as exc:
            raise IntegrityCheckFailed(
                f"schema check failed on {path}: {exc}"
            ) from exc
        if table_count == 0:
            raise IntegrityCheckFailed(
                f"target db {path} has no user tables "
                f"(empty or schemaless source)"
            )
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# execute_import — the transaction-scoped mutating entry point
# ---------------------------------------------------------------------------


def _cleanup_target(target: Path) -> None:
    """Best-effort recursive removal of a failed target directory.

    Idempotent: a missing dir is a no-op. Used in every exception path of
    :func:`execute_import` so a failed attempt never leaves a stray
    ``universes/<uid>/`` for ``reconcile`` to WARN about.
    """
    if target.exists():
        shutil.rmtree(target, ignore_errors=True)


def _transfer_one(plan: ImportPlan, source_dir: Path, target_dir: Path) -> None:
    """Copy or move every file in ``plan.file_plan.copy_files`` to ``target_dir``.

    Uses :func:`shutil.move` for ``mode == "move"`` so cross-device (EXDEV)
    falls back to copy+unlink automatically. ``shutil.copy2`` is used for
    ``mode == "copy"`` to preserve metadata. Errors propagate; the caller
    (execute_import) cleans up the target dir.
    """
    for name in plan.file_plan.copy_files:
        src = source_dir / name
        dst = target_dir / name
        if plan.mode == "move":
            shutil.move(str(src), str(dst))
        else:
            shutil.copy2(str(src), str(dst))


async def execute_import(
    plan: ImportPlan,
    registry: MultiverseRegistry,
    *,
    port_range: tuple[int, int] | None = None,
) -> str:
    """Execute ``plan`` against ``registry`` and return the plaintext API key.

    Transaction scope (plan §2.4 + Codex B2'/B3'): the unit
    ``allocate_port → mkdir → copy/move → integrity_check → manifest →
    registry.create_universe`` is retried up to :data:`_MAX_ATTEMPTS` times.

    Cleanup semantics differ by mode:

    * **copy mode**: every failure path removes the target dir. Source files
      are untouched, so the import can simply be retried. Safe by design.
    * **move mode**: a partial move has already relocated some source files
      into the target; auto-deleting the target would lose them permanently.
      On failure the target is LEFT IN PLACE so the operator can recover
      the files manually (plan §8.2: reverse-copy target → source). The
      exception still propagates so the import is reported as failed.

    The ``aiosqlite.IntegrityError`` (port collision on the partial UNIQUE
    INDEX ``idx_universes_port_live``) is the one case where cleanup is
    safe in both modes: it fires *after* the file transfer succeeded, so in
    move mode the target already holds the only copy and removing it would
    lose data — same leave-in-place rule applies, the operator manually
    reverses before retrying.

    ``port_range`` overrides the default ``(7890, 7989)`` window. Pass
    ``(config.universe_port_range_start, config.universe_port_range_end)``
    from the CLI to honor a custom deployment range. ``None`` keeps the
    historical default so existing tests are unaffected.

    UID preflight: :class:`UniverseAlreadyExistsError` is raised before the
    retry loop if ``plan.universe_id`` is already registered, so the
    subsequent ``create_universe`` PRIMARY KEY IntegrityError is not
    misclassified as a port race (which would retry 3 times and, in move
    mode, leave relocated files in target).

    Retry exhaustion → ``RuntimeError`` (caller exits 9).

    The plaintext API key is returned exactly once (the registry stores only
    its SHA-256 hash).
    """
    source_dir = Path(plan.source)
    target_dir = Path(plan.target)
    move_mode = plan.mode == "move"

    # UID preflight (Codex final review #5): raise before any file mutation
    # so an explicit-uid collision with an existing registry row cannot be
    # retried as a port race (in move mode the retry would have already
    # relocated source files into the target).
    existing = await registry.get_universe(plan.universe_id)
    if existing is not None:
        raise UniverseAlreadyExistsError(
            f"universe_id {plan.universe_id!r} already exists in registry"
        )

    if port_range is None:
        port_lo, port_hi = _DEFAULT_PORT_RANGE_START, _DEFAULT_PORT_RANGE_END
    else:
        port_lo, port_hi = port_range

    last_exc: Exception | None = None
    for attempt in range(1, _MAX_ATTEMPTS + 1):
        # Fresh target per attempt — a prior failed attempt's partial state
        # was cleaned (copy mode) or left for manual recovery (move mode) at
        # the end of the previous loop iteration. In move mode a retry is
        # only safe after the operator has manually recovered; we still loop
        # so the IntegrityError path keeps the target on disk consistently.
        target_dir.mkdir(parents=True, exist_ok=False)
        try:
            port = await registry.allocate_port(port_lo, port_hi)
            plan.port = port

            _transfer_one(plan, source_dir, target_dir)

            # Post-copy gate before any registry mutation. If the source was
            # corrupt or got written during copy (--force case), this refuses
            # to commit the import and the cleanup undoes the partial copy.
            _verify_target_db(target_dir / "gaottt.db")

            # Fresh managed manifest for the target — the source's manifest
            # (if any) was excluded from copy and is replaced here. ``managed``
            # is True so the backend's lease gate fires (a stray standalone
            # opener cannot quietly share the imported dir without winning
            # the lease).
            write_manifest(
                target_dir,
                UniverseManifest(
                    universe_id=plan.universe_id,
                    embedder_id=plan.embedder_id,
                    embedder_version=plan.embedder_version,
                    embedding_dim=plan.embedding_dim,
                    created_at=time.time(),
                    managed=True,
                ),
            )

            try:
                api_key = await registry.create_universe(
                    plan.universe_id,
                    plan.owner_label,
                    port,
                    plan.embedder_id,
                    plan.embedder_version,
                )
            except aiosqlite.IntegrityError as exc:
                # Port race with a concurrent supervisor. In copy mode,
                # retry the whole unit — a fresh allocate_port will pick the
                # next free port. In move mode the files are already in the
                # target; cleanup would lose them, so we leave the target
                # in place and surface the failure to the operator.
                logger.warning(
                    "importer attempt %d/%d: create_universe IntegrityError "
                    "(likely port race on %d): %s",
                    attempt, _MAX_ATTEMPTS, port, exc,
                )
                last_exc = exc
                if move_mode:
                    # Do NOT cleanup — moved files have no other copy.
                    # Re-raise so the operator can manually recover via
                    # the §8.2 reverse-copy procedure.
                    raise
                _cleanup_target(target_dir)
                continue

            return api_key

        except aiosqlite.IntegrityError as exc:
            # Move-mode IntegrityError from create_universe surfaces here
            # after the re-raise above. In copy mode this branch is only
            # reached if allocate_port or some other pre-transfer call
            # raises IntegrityError (defensive — currently allocate_port
            # raises RuntimeError, not IntegrityError).
            logger.warning(
                "importer attempt %d/%d: IntegrityError: %s",
                attempt, _MAX_ATTEMPTS, exc,
            )
            last_exc = exc
            if not move_mode:
                _cleanup_target(target_dir)
                continue
            # Move mode: target holds moved files; do not delete. Surface.
            raise
        except Exception:
            # Generic failure (copy error, integrity_check failure, ...).
            # In copy mode: clean up and re-raise — the source is intact so
            # the operator can fix the cause and retry cleanly. In move
            # mode: the target may hold the only copy of partially-moved
            # files; leave it in place for manual recovery (§8.2).
            if not move_mode:
                _cleanup_target(target_dir)
            else:
                logger.error(
                    "importer attempt %d/%d failed in move mode; target %s "
                    "left in place for manual recovery (do NOT re-run with "
                    "the same uid — recover files from target first).",
                    attempt, _MAX_ATTEMPTS, target_dir,
                )
            raise

    # Retry budget exhausted with only IntegrityError failures (copy mode).
    raise RuntimeError(
        f"could not allocate port after {_MAX_ATTEMPTS} attempts "
        f"(last error: {last_exc})"
    )


# Default port window — matches GaOTTTConfig.universe_port_range_{start,end}
# defaults (7890-7989, the canonical 100-port ceiling). Kept as module
# constants so execute_import's signature stays (plan, registry) -> str,
# which is pinned by the WP-1 contract.
_DEFAULT_PORT_RANGE_START = 7890
_DEFAULT_PORT_RANGE_END = 7989


__all__ = [
    "COPY_FILENAMES",
    "FilePlan",
    "ImportPlan",
    "IntegrityCheckFailed",
    "UniverseAlreadyExistsError",
    "build_import_plan",
    "compute_file_plan",
    "execute_import",
    "resolve_embedder_identity",
    "validate_universe_id",
]
